# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/ai_chat/core/common/buildflags/buildflags.gni")

brave_components_sync_driver_excluded_sources = [
  "glue/sync_engine_backend.cc",
  "glue/sync_engine_impl.cc",
  "sync_auth_manager.cc",
  "sync_internals_util.cc",
  "sync_service_impl.cc",
  "sync_session_durations_metrics_recorder.cc",
  "sync_user_settings_impl.cc",
]

brave_components_sync_driver_sources = [
  "//brave/chromium_src/components/sync/service/glue/sync_engine_backend.cc",
  "//brave/chromium_src/components/sync/service/glue/sync_engine_impl.cc",
  "//brave/chromium_src/components/sync/service/sync_auth_manager.cc",
  "//brave/chromium_src/components/sync/service/sync_internals_util.cc",
  "//brave/chromium_src/components/sync/service/sync_service_impl.cc",
  "//brave/chromium_src/components/sync/service/sync_session_durations_metrics_recorder.cc",
  "//brave/chromium_src/components/sync/service/sync_user_settings_impl.cc",
  "//brave/components/sync/service/brave_sync_auth_manager.cc",
  "//brave/components/sync/service/brave_sync_auth_manager.h",
  "//brave/components/sync/service/brave_sync_service_impl.cc",
  "//brave/components/sync/service/brave_sync_service_impl.h",
  "//brave/components/sync/service/brave_sync_stopped_reporter.cc",
  "//brave/components/sync/service/brave_sync_stopped_reporter.h",
  "//brave/components/sync/service/sync_service_impl_delegate.h",
]
brave_components_sync_driver_deps = [
  "//brave/components/ai_chat/core/common/buildflags",
  "//brave/components/brave_sync",
  "//brave/components/brave_sync:crypto",
  "//brave/components/brave_sync:features",
  "//brave/components/brave_sync:network_time_helper",
  "//brave/components/brave_sync:prefs",
  "//brave/components/constants",
]

if (enable_ai_chat) {
  brave_components_sync_driver_deps +=
      [ "//brave/components/ai_chat/core/common" ]
}
