# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

source_set("fingerprint_browser") {
  sources = [
    "persona_service_factory.cc",
    "persona_service_factory.h",
  ]

  public_deps = [ "//brave/components/fingerprint_browser/browser" ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/pref_registry",
    "//components/prefs",
    "//content/public/browser",
  ]
}
