# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

source_set("fingerprint_browser") {
  sources = [
    "fingerprint_proxy_service.cc",
    "fingerprint_proxy_service.h",
    "fingerprint_proxy_service_factory.cc",
    "fingerprint_proxy_service_factory.h",
    "persona_service_factory.cc",
    "persona_service_factory.h",
  ]

  public_deps = [
    "//brave/components/fingerprint_browser/browser",
    "//services/network/public/cpp",
  ]

  deps = [
    "//base",
    "//chrome/browser:browser_process",
    "//chrome/browser/profiles",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/os_crypt/async/browser",
    "//components/os_crypt/async/common",
    "//components/pref_registry",
    "//components/prefs",
    "//components/proxy_config",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/cert_verifier/public/mojom",
    "//services/network/public/mojom",
  ]
}
