# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_base_test_support_sources = [
  "//brave/base/test/launcher/teamcity_reporter.cc",
  "//brave/base/test/launcher/teamcity_reporter.h",
  "//brave/base/test/launcher/teamcity_service_messages.cc",
  "//brave/base/test/launcher/teamcity_service_messages.h",
]

brave_base_excluded_sources = [
  "check_is_test.cc",
  "feature_list.cc",
  "trace_event/memory_infra_background_allowlist.cc",
]

brave_base_sources = [
  "//brave/chromium_src/base/check_is_test.cc",
  "//brave/chromium_src/base/feature_list.cc",
  "//brave/chromium_src/base/trace_event/memory_infra_background_allowlist.cc",
]
