# Copyright (c) 2019 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

brave_net_excluded_sources = [
  "base/features.cc",
  "base/host_port_pair.cc",
  "base/proxy_server.cc",
  "base/proxy_string_util.cc",
  "cookies/canonical_cookie.cc",
  "cookies/cookie_access_delegate.cc",
  "cookies/cookie_monster.cc",
  "cookies/cookie_options.cc",
  "http/http_util.cc",
  "http/transport_security_persister.cc",
  "proxy_resolution/configured_proxy_resolution_service.cc",
  "quic/crypto/proof_verifier_chromium.cc",
  "socket/socks5_client_socket.cc",
  "socket/ssl_client_socket_impl.cc",
  "url_request/redirect_util.cc",
  "url_request/url_request_http_job.cc",
  "url_request/url_request_job.cc",
]

brave_net_sources = [
  "//brave/chromium_src/net/base/features.cc",
  "//brave/chromium_src/net/base/host_port_pair.cc",
  "//brave/chromium_src/net/base/proxy_server.cc",
  "//brave/chromium_src/net/base/proxy_string_util.cc",
  "//brave/chromium_src/net/cookies/canonical_cookie.cc",
  "//brave/chromium_src/net/cookies/cookie_access_delegate.cc",
  "//brave/chromium_src/net/cookies/cookie_monster.cc",
  "//brave/chromium_src/net/cookies/cookie_options.cc",
  "//brave/chromium_src/net/http/http_util.cc",
  "//brave/chromium_src/net/http/transport_security_persister.cc",
  "//brave/chromium_src/net/proxy_resolution/configured_proxy_resolution_service.cc",
  "//brave/chromium_src/net/quic/crypto/proof_verifier_chromium.cc",
  "//brave/chromium_src/net/socket/socks5_client_socket.cc",
  "//brave/chromium_src/net/socket/ssl_client_socket_impl.cc",
  "//brave/chromium_src/net/url_request/redirect_util.cc",
  "//brave/chromium_src/net/url_request/url_request_http_job.cc",
  "//brave/chromium_src/net/url_request/url_request_job.cc",
  "//brave/net/decentralized_dns/constants.cc",
  "//brave/net/decentralized_dns/constants.h",
  "//brave/net/http/partitioned_host_state_map.cc",
  "//brave/net/http/partitioned_host_state_map.h",
  "//brave/net/proxy_resolution/profile_proxy_config_service.cc",
  "//brave/net/proxy_resolution/profile_proxy_config_service.h",
  "//brave/net/proxy_resolution/proxy_config_service_tor.cc",
  "//brave/net/proxy_resolution/proxy_config_service_tor.h",
]
